name = "RegistryDIE"
uuid = "f70c353a-4330-4c86-a8a0-2d4da2974638"
repo = "https://github.com/DIE-BG/RegistryDIE"

[packages]
39a16359-57f0-4aba-960c-77dbb3b4d29c = { name = "CPIDataGT", path = "C/CPIDataGT" }
3d0454e0-948f-4743-b998-4d73da99f8a8 = { name = "InflationFunctions", path = "I/InflationFunctions" }
4d8691f9-d7cd-4649-8446-b9e4aa9b174c = { name = "Mudie", path = "M/Mudie" }
8f5dd8e8-af9a-4b7e-898c-9283934a1a2b = { name = "Inoptic", path = "I/Inoptic" }
938eba31-db9c-42f6-bde0-f3baed5865b3 = { name = "InflationEvalTools", path = "I/InflationEvalTools" }
bc2aee9a-d1f8-4cce-8750-9c1afc923989 = { name = "CPIDataBase", path = "C/CPIDataBase" }
